import json
from collections import Counter
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
MINI_PATH = PROJECT_ROOT / "data" / "skillbench_mini.json"
DEV_PATH = PROJECT_ROOT / "data" / "skillbench_dev.json"


def tool_task(
    task_id: str,
    instruction: str,
    gold_skills: list[str],
    expected_answer: str,
    task_type: str,
    notes: str,
    difficulty: str,
    benchmark_tags: list[str],
    source_inspiration: str,
    hard_negative_skills: list[str],
    argument_checks: list[dict],
    observation_checks: list[dict],
    final_answer_check: dict,
) -> dict:
    return {
        "task_id": task_id,
        "instruction": instruction,
        "gold_skills": gold_skills,
        "expected_answer": expected_answer,
        "task_type": task_type,
        "notes": notes,
        "gold_sequence": list(gold_skills),
        "difficulty": difficulty,
        "benchmark_tags": benchmark_tags,
        "source_inspiration": source_inspiration,
        "hard_negative_skills": hard_negative_skills,
        "expected_checks": {
            "arguments": argument_checks,
            "observations": observation_checks,
            "final_answer": final_answer_check,
            "faithfulness": True,
        },
    }


def abstain_task(
    task_id: str,
    instruction: str,
    expected_answer: str,
    task_type: str,
    notes: str,
    difficulty: str,
    benchmark_tags: list[str],
    source_inspiration: str,
    hard_negative_skills: list[str],
    final_answer_check: dict,
) -> dict:
    return {
        "task_id": task_id,
        "instruction": instruction,
        "gold_skills": [],
        "expected_answer": expected_answer,
        "task_type": task_type,
        "notes": notes,
        "gold_sequence": [],
        "difficulty": difficulty,
        "benchmark_tags": benchmark_tags,
        "source_inspiration": source_inspiration,
        "hard_negative_skills": hard_negative_skills,
        "expected_checks": {
            "final_answer": final_answer_check,
            "faithfulness": True,
        },
    }


NEW_DEV_TASKS = [
    abstain_task(
        "dev_121",
        "What does the word calculate mean in a tool-using agent? Answer conceptually, do not compute anything.",
        "A conceptual explanation of calculation, without using a calculator.",
        "no_tool",
        "Hard no-tool task containing a calculator trigger word.",
        "hard",
        ["hard_no_tool", "tool_trigger_irrelevance", "calculator_negative"],
        "BFCL_irrelevance",
        ["calculator", "equation_solver"],
        {"regex": [r"(compute|arithmetic|calculation|calculate)"]},
    ),
    abstain_task(
        "dev_122",
        "I am not asking you to summarize anything. Explain why summaries can lose important details.",
        "An explanation that summaries compress text and may omit details.",
        "no_tool",
        "Hard no-tool task containing summarize as a quoted concept.",
        "hard",
        ["hard_no_tool", "tool_trigger_irrelevance", "summarizer_negative"],
        "BFCL_irrelevance",
        ["summarizer", "text_rewriter"],
        {"regex": [r"(summar|compress|detail|omit)"]},
    ),
    abstain_task(
        "dev_123",
        "Do not translate this sentence. Explain why translation direction matters for tool calling.",
        "Translation direction decides whether zh-en or en-zh should be selected.",
        "no_tool",
        "Hard no-tool task that mentions translation but asks for explanation.",
        "hard",
        ["hard_no_tool", "translation_direction_negative"],
        "MetaTool_tool_decision",
        ["translator_zh_en", "translator_en_zh"],
        {"regex": [r"(direction|source|target|translation)"]},
    ),
    abstain_task(
        "dev_124",
        "What is the difference between a keyword and an entity in information extraction?",
        "Keywords are topical terms, while entities are named people, organizations, or locations.",
        "no_tool",
        "Conceptual comparison of two extraction skills without extraction input.",
        "hard",
        ["hard_no_tool", "semantic_confusion", "extraction_negative"],
        "BFCL_irrelevance",
        ["keyword_extractor", "entity_extractor"],
        {"regex": [r"(keyword|term)", r"(entity|person|organization|location)"]},
    ),
    abstain_task(
        "dev_125",
        "In words, why can percentage and ratio questions be confused by an agent?",
        "Both involve comparing numbers, but percentage uses a per-hundred scale while ratio compares quantities directly.",
        "no_tool",
        "Conceptual no-tool contrast for similar math tools.",
        "hard",
        ["hard_no_tool", "semantic_confusion", "math_negative"],
        "MetaTool_tool_decision",
        ["percentage_calculator", "ratio_calculator"],
        {"regex": [r"(percentage|percent)", r"(ratio|compare)"]},
    ),
    abstain_task(
        "dev_126",
        "Describe when an agent should refuse an unsupported tool request.",
        "It should refuse when no registered tool can safely perform the requested external action.",
        "no_tool",
        "No-tool policy explanation with unsupported-tool wording.",
        "hard",
        ["hard_no_tool", "unsupported_concept"],
        "StableToolBench_evaluation_setting",
        ["intent_classifier", "paper_qa"],
        {"regex": [r"(refuse|unsupported|cannot|can't|unable|no registered)"]},
    ),
    abstain_task(
        "dev_127",
        "What does JSON validation mean conceptually? Do not validate any JSON.",
        "JSON validation checks whether a string follows JSON syntax and can be parsed.",
        "no_tool",
        "Mentions json validation but provides no JSON object to validate.",
        "hard",
        ["hard_no_tool", "json_negative"],
        "BFCL_irrelevance",
        ["json_validator"],
        {"regex": [r"(json|syntax|valid|parse)"]},
    ),
    abstain_task(
        "dev_128",
        "Why is final-answer faithfulness important after a tool call?",
        "The final answer should stay supported by the observation instead of inventing unsupported results.",
        "no_tool",
        "Evaluation concept question that should not call summarizer.",
        "hard",
        ["hard_no_tool", "evaluation_concept"],
        "StableToolBench_evaluation_setting",
        ["summarizer", "paper_qa"],
        {"regex": [r"(faithful|faithfulness|observation|tool|supported)"]},
    ),
    abstain_task(
        "dev_129",
        "Define observation in an agent pipeline in one sentence.",
        "An observation is the result returned by a skill or environment after an action.",
        "no_tool",
        "Agent concept definition with no need for paper QA.",
        "hard",
        ["hard_no_tool", "agent_pipeline_concept"],
        "ToolBench_trajectory_taxonomy",
        ["paper_qa", "summarizer"],
        {"regex": [r"(observation|result|returned|tool|skill)"]},
    ),
    abstain_task(
        "dev_130",
        "List two risks of using a Python execution tool in an agent system.",
        "Possible risks include unsafe code execution, data leakage, file access, or system command abuse.",
        "no_tool",
        "Security explanation that mentions python_executor without code.",
        "hard",
        ["hard_no_tool", "safety_concept"],
        "APIBank_tool_use_safety",
        ["python_executor"],
        {"regex": [r"(risk|unsafe|security|code|command|file)"]},
    ),
    abstain_task(
        "dev_131",
        "Convert this value to meters.",
        "Ask for the numeric value and source unit before converting.",
        "missing_info",
        "Missing numeric value and source unit for unit conversion.",
        "hard",
        ["missing_info", "missing_argument", "unit_conversion"],
        "BFCL_missing_param",
        ["unit_converter"],
        {"regex": [r"(need|provide|missing|what|which).*(value|number|unit)"]},
    ),
    abstain_task(
        "dev_132",
        "Calculate the percentage for this group.",
        "Ask for the part and total values needed to compute a percentage.",
        "missing_info",
        "Missing both numerator and denominator for percentage calculation.",
        "hard",
        ["missing_info", "missing_argument", "percentage"],
        "BFCL_missing_param",
        ["percentage_calculator"],
        {"regex": [r"(need|provide|missing|what).*(part|total|number|value)"]},
    ),
    abstain_task(
        "dev_133",
        "Sort the list I mentioned earlier.",
        "Ask the user to provide the list and sort order.",
        "missing_info",
        "References unavailable earlier content.",
        "hard",
        ["missing_info", "ellipsis", "list_operation"],
        "BFCL_missing_param",
        ["list_sorter"],
        {"regex": [r"(list|items|provide|need)"]},
    ),
    abstain_task(
        "dev_134",
        "Extract the dates from the document.",
        "Ask the user to provide the document text.",
        "missing_info",
        "Missing source text for regex extraction.",
        "hard",
        ["missing_info", "missing_text", "regex"],
        "BFCL_missing_param",
        ["regex_extractor"],
        {"regex": [r"(document|text|provide|need)"]},
    ),
    abstain_task(
        "dev_135",
        "Translate the sentence into English.",
        "Ask the user to provide the sentence to translate.",
        "missing_info",
        "Missing source sentence for translation.",
        "hard",
        ["missing_info", "translation", "missing_text"],
        "BFCL_missing_param",
        ["translator_zh_en"],
        {"regex": [r"(sentence|text|provide|need)"]},
    ),
    abstain_task(
        "dev_136",
        "Validate this JSON.",
        "Ask the user to provide the JSON string.",
        "missing_info",
        "Missing JSON content for validation.",
        "hard",
        ["missing_info", "json", "missing_text"],
        "BFCL_missing_param",
        ["json_validator"],
        {"regex": [r"(json|content|string|provide|need)"]},
    ),
    abstain_task(
        "dev_137",
        "Summarize the passage.",
        "Ask the user to provide the passage text.",
        "missing_info",
        "Missing source passage for summarization.",
        "hard",
        ["missing_info", "summarization", "missing_text"],
        "BFCL_missing_param",
        ["summarizer"],
        {"regex": [r"(passage|text|provide|need)"]},
    ),
    abstain_task(
        "dev_138",
        "Compute the mean and median for my numbers.",
        "Ask the user to provide the numbers.",
        "missing_info",
        "Missing numeric sequence for statistics calculation.",
        "hard",
        ["missing_info", "statistics", "missing_values"],
        "BFCL_missing_param",
        ["statistics_calculator"],
        {"regex": [r"(numbers|values|provide|need)"]},
    ),
    abstain_task(
        "dev_139",
        "Put those results into a table.",
        "Ask the user to provide the results to format.",
        "missing_info",
        "Missing referenced content for table formatting.",
        "hard",
        ["missing_info", "ellipsis", "formatting"],
        "BFCL_missing_param",
        ["table_formatter"],
        {"regex": [r"(results|data|provide|need)"]},
    ),
    abstain_task(
        "dev_140",
        "Solve the equation for x.",
        "Ask the user to provide the equation.",
        "missing_info",
        "Missing equation string for equation_solver.",
        "hard",
        ["missing_info", "equation", "missing_expression"],
        "BFCL_missing_param",
        ["equation_solver"],
        {"regex": [r"(equation|provide|need|missing)"]},
    ),
    abstain_task(
        "dev_141",
        "Book a real flight from Beijing to Shanghai for tomorrow morning.",
        "Refuse or explain that no booking skill is available.",
        "unsupported_tool",
        "External real-world booking is unsupported by the local skill library.",
        "hard",
        ["unsupported_tool", "external_action", "booking"],
        "BFCL_missing_func",
        ["intent_classifier", "email_drafter"],
        {"regex": [r"(cannot|can't|unable|unsupported|no.*tool|not able)"]},
    ),
    abstain_task(
        "dev_142",
        "Open my browser and download the latest stock prices.",
        "Refuse or explain that browser automation and live market download are unsupported.",
        "unsupported_tool",
        "Network/browser action is outside the skill library.",
        "hard",
        ["unsupported_tool", "external_action", "network"],
        "BFCL_missing_func",
        ["python_executor", "topic_classifier"],
        {"regex": [r"(cannot|can't|unable|unsupported|no.*tool|not able)"]},
    ),
    abstain_task(
        "dev_143",
        "Send an actual email to Professor Lee right now.",
        "Explain that drafting is possible but sending real email is unsupported.",
        "unsupported_tool",
        "Similar to email_drafter but requires external sending.",
        "hard",
        ["unsupported_tool", "external_action", "email"],
        "BFCL_missing_func",
        ["email_drafter"],
        {"regex": [r"(cannot|can't|unable|unsupported|draft|send)"]},
    ),
    abstain_task(
        "dev_144",
        "Query live weather in Beijing for tomorrow.",
        "Explain that live weather lookup is not available in this local skill set.",
        "unsupported_tool",
        "Live API/tool request with no registered weather skill.",
        "hard",
        ["unsupported_tool", "external_api", "weather"],
        "BFCL_missing_func",
        ["topic_classifier", "paper_qa"],
        {"regex": [r"(cannot|can't|unable|unsupported|weather|no.*tool)"]},
    ),
    abstain_task(
        "dev_145",
        "Upload these experiment results to GitHub.",
        "Explain that repository upload is unsupported by the registered local skills.",
        "unsupported_tool",
        "External GitHub write action is not a registered skill.",
        "hard",
        ["unsupported_tool", "external_action", "github"],
        "BFCL_missing_func",
        ["python_executor", "table_formatter"],
        {"regex": [r"(cannot|can't|unable|unsupported|github|no.*tool)"]},
    ),
    tool_task(
        "dev_146",
        "Calculate 18 / 72.",
        ["calculator"],
        "0.25",
        "single_skill",
        "Minimal pair: arithmetic value, not percentage or ratio wording.",
        "medium",
        ["minimal_pair", "math", "calculator"],
        "MetaTool_single_tool",
        ["percentage_calculator", "ratio_calculator", "statistics_calculator"],
        [{"skill": "calculator", "contains": ["18", "72"]}],
        [{"skill": "calculator", "contains": ["0.25"]}],
        {"contains": ["0.25"]},
    ),
    tool_task(
        "dev_147",
        "What percentage is 18 of 72?",
        ["percentage_calculator"],
        "25%",
        "single_skill",
        "Minimal pair: same numbers as ratio/calculator but asks percentage.",
        "medium",
        ["minimal_pair", "math", "percentage"],
        "MetaTool_single_tool",
        ["calculator", "ratio_calculator", "statistics_calculator"],
        [{"skill": "percentage_calculator", "contains": ["18", "72"]}],
        [{"skill": "percentage_calculator", "contains": ["25"]}],
        {"contains": ["25"]},
    ),
    tool_task(
        "dev_148",
        "Find the ratio of 18 to 72.",
        ["ratio_calculator"],
        "1:4",
        "single_skill",
        "Minimal pair: ratio wording with same numbers as percentage.",
        "medium",
        ["minimal_pair", "math", "ratio"],
        "MetaTool_single_tool",
        ["calculator", "percentage_calculator", "statistics_calculator"],
        [{"skill": "ratio_calculator", "contains": ["18", "72"]}],
        [{"skill": "ratio_calculator", "contains": ["1:4"]}],
        {"contains": ["1:4"]},
    ),
    tool_task(
        "dev_149",
        "Solve equation 3*x + 6 = 21.",
        ["equation_solver"],
        "x=5",
        "single_skill",
        "Minimal pair: equation solving, not raw arithmetic.",
        "medium",
        ["minimal_pair", "math", "equation"],
        "APIBank_level1",
        ["calculator", "statistics_calculator"],
        [{"skill": "equation_solver", "contains": ["3*x", "21"]}],
        [{"skill": "equation_solver", "contains": ["x=5"]}],
        {"contains": ["x=5"]},
    ),
    tool_task(
        "dev_150",
        "Compute statistics for 18 and 72, especially the mean.",
        ["statistics_calculator"],
        "mean=45",
        "single_skill",
        "Minimal pair: average/statistics instead of arithmetic division.",
        "medium",
        ["minimal_pair", "math", "statistics"],
        "MetaTool_single_tool",
        ["calculator", "ratio_calculator", "percentage_calculator"],
        [{"skill": "statistics_calculator", "contains": ["18", "72"]}],
        [{"skill": "statistics_calculator", "contains": ["mean=45"]}],
        {"contains": ["mean=45"]},
    ),
    tool_task(
        "dev_151",
        "Find key terms in: Alice emailed Bob about SkillBench retrieval.",
        ["keyword_extractor"],
        "Keywords include Alice and SkillBench.",
        "single_skill",
        "Minimal pair: topical terms, not named-entity schema.",
        "medium",
        ["minimal_pair", "extraction", "keywords"],
        "ToolBench_qrels",
        ["entity_extractor", "regex_extractor", "todo_extractor"],
        [{"skill": "keyword_extractor", "contains": ["Alice", "SkillBench"]}],
        [{"skill": "keyword_extractor", "contains": ["Keywords"]}],
        {"contains": ["Keywords"]},
    ),
    tool_task(
        "dev_152",
        "Pull entities from: Alice met Bob at OpenAI in Beijing.",
        ["entity_extractor"],
        "Entities include Alice, Bob, OpenAI, and Beijing.",
        "single_skill",
        "Minimal pair: named entities, not keywords.",
        "medium",
        ["minimal_pair", "extraction", "entities"],
        "ToolBench_qrels",
        ["keyword_extractor", "regex_extractor", "topic_classifier"],
        [{"skill": "entity_extractor", "contains": ["Alice", "OpenAI", "Beijing"]}],
        [{"skill": "entity_extractor", "contains": ["Alice", "OpenAI", "Beijing"]}],
        {"contains": ["Entities"]},
    ),
    tool_task(
        "dev_153",
        "Extract contact patterns from: kai@example.com and 2026-08-01.",
        ["regex_extractor"],
        "Regex matches include kai@example.com and 2026-08-01.",
        "single_skill",
        "Minimal pair: regex patterns, not entities or keywords.",
        "medium",
        ["minimal_pair", "extraction", "regex"],
        "ToolBench_qrels",
        ["keyword_extractor", "entity_extractor"],
        [{"skill": "regex_extractor", "contains": ["kai@example.com", "2026-08-01"]}],
        [{"skill": "regex_extractor", "contains": ["kai@example.com", "2026-08-01"]}],
        {"contains": ["kai@example.com", "2026-08-01"]},
    ),
    tool_task(
        "dev_154",
        "Extract todos from: We must rerun BM25; remember to save metrics.",
        ["todo_extractor"],
        "Todos include rerun BM25 and save metrics.",
        "single_skill",
        "Minimal pair: action-item extraction, not keyword extraction.",
        "medium",
        ["minimal_pair", "extraction", "todos"],
        "APIBank_level1",
        ["keyword_extractor", "meeting_notes_extractor"],
        [{"skill": "todo_extractor", "contains": ["rerun", "save"]}],
        [{"skill": "todo_extractor", "contains": ["rerun", "save"]}],
        {"contains": ["Todos"]},
    ),
    tool_task(
        "dev_155",
        "Summarize this text: Agents retrieve skills, call tools, and ground final answers.",
        ["summarizer"],
        "Summary of the agent pipeline.",
        "single_skill",
        "Minimal pair: summary instead of title or outline.",
        "medium",
        ["minimal_pair", "generation", "summarization"],
        "MetaTool_single_tool",
        ["title_generator", "outline_generator", "question_generator"],
        [{"skill": "summarizer", "contains": ["Agents retrieve skills"]}],
        [{"skill": "summarizer", "contains": ["Summary"]}],
        {"contains": ["Summary"]},
    ),
    tool_task(
        "dev_156",
        "Create a title for: agents retrieve skills before calling them.",
        ["title_generator"],
        "Title about agents retrieving skills.",
        "single_skill",
        "Minimal pair: title, not summary or outline.",
        "medium",
        ["minimal_pair", "generation", "title"],
        "MetaTool_single_tool",
        ["summarizer", "outline_generator", "question_generator"],
        [{"skill": "title_generator", "contains": ["agents", "skills"]}],
        [{"skill": "title_generator", "contains": ["Title"]}],
        {"contains": ["Title"]},
    ),
    tool_task(
        "dev_157",
        "Build an outline about skill-calling evaluation.",
        ["outline_generator"],
        "Outline with introduction, key points, evidence, and conclusion.",
        "single_skill",
        "Minimal pair: outline structure, not summary.",
        "medium",
        ["minimal_pair", "generation", "outline"],
        "MetaTool_single_tool",
        ["summarizer", "title_generator", "question_generator"],
        [{"skill": "outline_generator", "contains": ["skill-calling evaluation"]}],
        [{"skill": "outline_generator", "contains": ["Outline"]}],
        {"contains": ["Outline"]},
    ),
    tool_task(
        "dev_158",
        "Write study questions about tool-use decisions.",
        ["question_generator"],
        "Questions about tool-use decisions.",
        "single_skill",
        "Minimal pair: question generation, not outline or title.",
        "medium",
        ["minimal_pair", "generation", "questions"],
        "MetaTool_single_tool",
        ["outline_generator", "title_generator", "summarizer"],
        [{"skill": "question_generator", "contains": ["tool-use decisions"]}],
        [{"skill": "question_generator", "contains": ["Questions"]}],
        {"contains": ["Questions"]},
    ),
    tool_task(
        "dev_159",
        "Fix grammar: they is testing a agent.",
        ["grammar_corrector"],
        "They are testing an agent.",
        "single_skill",
        "Minimal pair: grammar correction, not general rewrite.",
        "medium",
        ["minimal_pair", "editing", "grammar"],
        "APIBank_level1",
        ["text_rewriter", "tone_converter"],
        [{"skill": "grammar_corrector", "contains": ["they is", "a agent"]}],
        [{"skill": "grammar_corrector", "contains": ["they are", "an agent"]}],
        {"contains": ["they are", "an agent"]},
    ),
    tool_task(
        "dev_160",
        "Make this request formal: send logs today.",
        ["tone_converter"],
        "Formal tone request.",
        "single_skill",
        "Minimal pair: tone conversion, not grammar or rewrite.",
        "medium",
        ["minimal_pair", "editing", "tone"],
        "APIBank_level1",
        ["grammar_corrector", "text_rewriter", "email_drafter"],
        [{"skill": "tone_converter", "contains": ["formal", "send logs"]}],
        [{"skill": "tone_converter", "contains": ["Formal tone"]}],
        {"contains": ["Formal tone"]},
    ),
    tool_task(
        "dev_161",
        "A report says 45 passed out of 180; compute the percentage.",
        ["percentage_calculator"],
        "25%",
        "single_skill",
        "Argument-heavy percentage calculation with implicit part/whole mapping.",
        "medium",
        ["argument_heavy", "percentage", "input_construction"],
        "BFCL_missing_param",
        ["calculator", "ratio_calculator"],
        [{"skill": "percentage_calculator", "contains": ["45", "180"]}],
        [{"skill": "percentage_calculator", "contains": ["25"]}],
        {"contains": ["25"]},
    ),
    tool_task(
        "dev_162",
        "Convert 1250 g to kg.",
        ["unit_converter"],
        "1.25 kg",
        "single_skill",
        "Argument-heavy unit conversion with value, source unit, and target unit.",
        "medium",
        ["argument_heavy", "unit_conversion", "input_construction"],
        "BFCL_missing_param",
        ["calculator", "percentage_calculator"],
        [{"skill": "unit_converter", "contains": ["1250", "g", "kg"]}],
        [{"skill": "unit_converter", "contains": ["1.25", "kg"]}],
        {"contains": ["1.25", "kg"]},
    ),
    tool_task(
        "dev_163",
        "Solve equation 5*x - 10 = 40.",
        ["equation_solver"],
        "x=10",
        "single_skill",
        "Argument-heavy equation solving with linear expression.",
        "medium",
        ["argument_heavy", "equation", "input_construction"],
        "APIBank_level1",
        ["calculator", "statistics_calculator"],
        [{"skill": "equation_solver", "contains": ["5*x", "40"]}],
        [{"skill": "equation_solver", "contains": ["x=10"]}],
        {"contains": ["x=10"]},
    ),
    tool_task(
        "dev_164",
        "For 4, 8, 12, 16, give mean and median.",
        ["statistics_calculator"],
        "mean=10, median=10",
        "single_skill",
        "Argument-heavy statistics with multiple numbers.",
        "medium",
        ["argument_heavy", "statistics", "input_construction"],
        "APIBank_level1",
        ["calculator", "number_sequence_analyzer"],
        [{"skill": "statistics_calculator", "contains": ["4", "8", "12", "16"]}],
        [{"skill": "statistics_calculator", "contains": ["mean=10", "median=10"]}],
        {"contains": ["mean=10", "median=10"]},
    ),
    tool_task(
        "dev_165",
        "Find dates and emails in: contact lee@example.com by 2026-09-12.",
        ["regex_extractor"],
        "lee@example.com and 2026-09-12",
        "single_skill",
        "Argument-heavy regex extraction with two pattern families.",
        "medium",
        ["argument_heavy", "regex", "input_construction"],
        "ToolBench_qrels",
        ["keyword_extractor", "entity_extractor"],
        [{"skill": "regex_extractor", "contains": ["lee@example.com", "2026-09-12"]}],
        [{"skill": "regex_extractor", "contains": ["lee@example.com", "2026-09-12"]}],
        {"contains": ["lee@example.com", "2026-09-12"]},
    ),
    tool_task(
        "dev_166",
        "Check JSON: {\"task\":\"eval\",\"ok\":true}",
        ["json_validator"],
        "JSON valid",
        "single_skill",
        "Argument-heavy JSON validation with complete object.",
        "medium",
        ["argument_heavy", "json", "input_construction"],
        "APIBank_level1",
        ["table_formatter", "csv_summarizer"],
        [{"skill": "json_validator", "contains": ["task", "ok"]}],
        [{"skill": "json_validator", "contains": ["JSON valid"]}],
        {"contains": ["JSON valid"]},
    ),
    tool_task(
        "dev_167",
        "Summarize CSV data:\nname,score\nA,2\nB,4",
        ["csv_summarizer"],
        "rows=2, columns=2, score mean=3",
        "single_skill",
        "Argument-heavy CSV summarization where newlines are semantically important.",
        "medium",
        ["argument_heavy", "csv", "input_construction"],
        "APIBank_level1",
        ["table_formatter", "json_validator"],
        [{"skill": "csv_summarizer", "contains": ["name,score", "A,2", "B,4"]}],
        [{"skill": "csv_summarizer", "contains": ["rows=2", "columns=2", "mean=3"]}],
        {"contains": ["rows=2", "columns=2"]},
    ),
    tool_task(
        "dev_168",
        "How many days are between 2026-01-15 and 2026-02-04?",
        ["date_difference_calculator"],
        "20 days",
        "single_skill",
        "Argument-heavy date difference with two ISO dates.",
        "medium",
        ["argument_heavy", "date", "input_construction"],
        "APIBank_level1",
        ["calculator", "statistics_calculator"],
        [{"skill": "date_difference_calculator", "contains": ["2026-01-15", "2026-02-04"]}],
        [{"skill": "date_difference_calculator", "contains": ["20 days"]}],
        {"contains": ["20 days"]},
    ),
    tool_task(
        "dev_169",
        "From values 1, 4, 7, 10, 13 keep values between 4 and 10.",
        ["range_filter"],
        "4, 7, 10",
        "single_skill",
        "Argument-heavy range filtering with inclusive bounds.",
        "medium",
        ["argument_heavy", "range_filter", "input_construction"],
        "APIBank_level1",
        ["list_sorter", "statistics_calculator"],
        [{"skill": "range_filter", "contains": ["1", "4", "7", "10", "13"]}],
        [{"skill": "range_filter", "contains": ["4", "7", "10"]}],
        {"contains": ["4", "7", "10"]},
    ),
    tool_task(
        "dev_170",
        "Run this restricted Python code: numbers=[1,2,3]; sum(numbers)",
        ["python_executor"],
        "6",
        "single_skill",
        "Argument-heavy safe code execution with expression result.",
        "medium",
        ["argument_heavy", "python_executor", "safety"],
        "APIBank_level1",
        ["calculator", "statistics_calculator"],
        [{"skill": "python_executor", "contains": ["numbers", "sum"]}],
        [{"skill": "python_executor", "contains": ["6"]}],
        {"contains": ["6"]},
    ),
    tool_task(
        "dev_171",
        "Turn this meeting note into action items and present them as a table: Alice must update retriever; Bob should verify metrics.",
        ["todo_extractor", "table_formatter"],
        "Action items in a table.",
        "multi_skill",
        "Implicit multi-skill: extract todos and format them as a table.",
        "hard",
        ["implicit_multi_skill", "todo", "table", "input_dependency"],
        "ToolBench_trajectory_taxonomy",
        ["meeting_notes_extractor", "keyword_extractor"],
        [
            {"skill": "todo_extractor", "contains": ["must update", "should verify"]},
            {"skill": "table_formatter", "regex": [r"(Todos|update|verify|\$PREVIOUS_OUTPUT)"]},
        ],
        [
            {"skill": "todo_extractor", "contains": ["update", "verify"]},
            {"skill": "table_formatter", "contains": ["Table"]},
        ],
        {"contains": ["Table"]},
    ),
    tool_task(
        "dev_172",
        "Give this paragraph a concise headline and list the key terms in that headline: Skill retrieval narrows tools before execution.",
        ["title_generator", "keyword_extractor"],
        "Title plus keywords.",
        "multi_skill",
        "Implicit multi-skill: title generation followed by keyword extraction.",
        "hard",
        ["implicit_multi_skill", "title", "keywords", "input_dependency"],
        "MetaTool_multi_tool",
        ["summarizer", "outline_generator"],
        [
            {"skill": "title_generator", "contains": ["Skill retrieval narrows tools"]},
            {"skill": "keyword_extractor", "regex": [r"(Title|retrieval|tools|\$PREVIOUS_OUTPUT)"]},
        ],
        [
            {"skill": "title_generator", "contains": ["Title"]},
            {"skill": "keyword_extractor", "contains": ["Keywords"]},
        ],
        {"contains": ["Keywords"]},
    ),
    tool_task(
        "dev_173",
        "Make this complaint polite and judge whether the rewritten version remains negative: I hate the slow benchmark runs.",
        ["tone_converter", "sentiment_analyzer"],
        "Polite rewrite and negative sentiment.",
        "multi_skill",
        "Implicit multi-skill: tone conversion and sentiment on rewritten output.",
        "hard",
        ["implicit_multi_skill", "tone", "sentiment", "input_dependency"],
        "MetaTool_multi_tool",
        ["grammar_corrector", "text_rewriter"],
        [
            {"skill": "tone_converter", "contains": ["polite", "hate"]},
            {"skill": "sentiment_analyzer", "regex": [r"(Formal tone|hate|\$PREVIOUS_OUTPUT)"]},
        ],
        [
            {"skill": "tone_converter", "contains": ["Formal tone"]},
            {"skill": "sentiment_analyzer", "contains": ["Sentiment"]},
        ],
        {"contains": ["sentiment_analyzer"]},
    ),
    tool_task(
        "dev_174",
        "Clean the grammar and estimate readability: they is testing a agent. It runs tools.",
        ["grammar_corrector", "readability_scorer"],
        "Grammar correction plus readability score.",
        "multi_skill",
        "Implicit multi-skill: grammar correction and readability on corrected text.",
        "hard",
        ["implicit_multi_skill", "grammar", "readability", "input_dependency"],
        "MetaTool_multi_tool",
        ["text_rewriter", "summarizer"],
        [
            {"skill": "grammar_corrector", "contains": ["they is", "a agent"]},
            {"skill": "readability_scorer", "regex": [r"(Grammar corrected|\$PREVIOUS_OUTPUT)"]},
        ],
        [
            {"skill": "grammar_corrector", "contains": ["they are", "an agent"]},
            {"skill": "readability_scorer", "contains": ["Readability"]},
        ],
        {"contains": ["Readability"]},
    ),
    tool_task(
        "dev_175",
        "Identify entities and organize them as a table: Alice visited OpenAI in Beijing.",
        ["entity_extractor", "table_formatter"],
        "Entities organized as table.",
        "multi_skill",
        "Implicit multi-skill: entity extraction and table formatting.",
        "hard",
        ["implicit_multi_skill", "entities", "table", "input_dependency"],
        "ToolBench_trajectory_taxonomy",
        ["keyword_extractor", "regex_extractor"],
        [
            {"skill": "entity_extractor", "contains": ["Alice", "OpenAI", "Beijing"]},
            {"skill": "table_formatter", "regex": [r"(Entities|Alice|OpenAI|\$PREVIOUS_OUTPUT)"]},
        ],
        [
            {"skill": "entity_extractor", "contains": ["Alice", "OpenAI", "Beijing"]},
            {"skill": "table_formatter", "contains": ["Table"]},
        ],
        {"contains": ["Table"]},
    ),
    tool_task(
        "dev_176",
        "Extract the dates and summarize what was found: email on 2026-08-01 and meeting on 2026-08-03.",
        ["regex_extractor", "summarizer"],
        "Date extraction summary.",
        "multi_skill",
        "Implicit multi-skill: regex extraction followed by summary.",
        "hard",
        ["implicit_multi_skill", "regex", "summary", "input_dependency"],
        "MetaTool_multi_tool",
        ["keyword_extractor", "date_difference_calculator"],
        [
            {"skill": "regex_extractor", "contains": ["2026-08-01", "2026-08-03"]},
            {"skill": "summarizer", "regex": [r"(Regex matches|2026-08-01|\$PREVIOUS_OUTPUT)"]},
        ],
        [
            {"skill": "regex_extractor", "contains": ["2026-08-01", "2026-08-03"]},
            {"skill": "summarizer", "contains": ["Summary"]},
        ],
        {"contains": ["Summary"]},
    ),
    tool_task(
        "dev_177",
        "Calculate 14 * 6, then summarize the result in one sentence.",
        ["calculator", "summarizer"],
        "84 summarized in one sentence.",
        "multi_skill",
        "Explicit then task kept as a control among implicit multi-skill cases.",
        "hard",
        ["implicit_multi_skill", "calculation", "summary", "control_then"],
        "MetaTool_multi_tool",
        ["statistics_calculator", "readability_scorer"],
        [
            {"skill": "calculator", "contains": ["14", "6"]},
            {"skill": "summarizer", "regex": [r"(84|\$PREVIOUS_OUTPUT)"]},
        ],
        [
            {"skill": "calculator", "contains": ["84"]},
            {"skill": "summarizer", "contains": ["Summary"]},
        ],
        {"contains": ["Summary"]},
    ),
    tool_task(
        "dev_178",
        "Translate hello skill agent into Chinese, then extract keywords from the translation.",
        ["translator_en_zh", "keyword_extractor"],
        "Chinese translation plus keywords.",
        "multi_skill",
        "Explicit then task focused on translation direction and dependent extraction.",
        "hard",
        ["implicit_multi_skill", "translation_direction", "keywords", "control_then"],
        "MetaTool_multi_tool",
        ["translator_zh_en", "summarizer"],
        [
            {"skill": "translator_en_zh", "contains": ["hello", "skill", "agent"]},
            {"skill": "keyword_extractor", "regex": [r"(\$PREVIOUS_OUTPUT|浣|skill|agent)"]},
        ],
        [
            {"skill": "translator_en_zh", "regex": [r"(浣|鎶|agent|placeholder)"]},
            {"skill": "keyword_extractor", "contains": ["Keywords"]},
        ],
        {"contains": ["Keywords"]},
    ),
    tool_task(
        "dev_179",
        "Create a checklist and draft an email about running SkillBench experiments.",
        ["checklist_generator", "email_drafter"],
        "Checklist plus email draft.",
        "multi_skill",
        "Implicit multi-skill: generate checklist and draft an email.",
        "hard",
        ["implicit_multi_skill", "checklist", "email"],
        "ToolBench_trajectory_taxonomy",
        ["outline_generator", "todo_extractor"],
        [
            {"skill": "checklist_generator", "contains": ["running SkillBench experiments"]},
            {"skill": "email_drafter", "contains": ["running SkillBench experiments"]},
        ],
        [
            {"skill": "checklist_generator", "contains": ["Checklist"]},
            {"skill": "email_drafter", "contains": ["Email draft"]},
        ],
        {"contains": ["Email draft"]},
    ),
    tool_task(
        "dev_180",
        "Classify the topic and rewrite the text more cleanly: neural agents retrieve tools from a dataset.",
        ["topic_classifier", "text_rewriter"],
        "Machine-learning topic plus rewritten text.",
        "multi_skill",
        "Implicit multi-skill: topic classification and clean rewrite.",
        "hard",
        ["implicit_multi_skill", "topic", "rewrite"],
        "MetaTool_multi_tool",
        ["intent_classifier", "summarizer"],
        [
            {"skill": "topic_classifier", "contains": ["neural agents", "dataset"]},
            {"skill": "text_rewriter", "contains": ["neural agents retrieve tools"]},
        ],
        [
            {"skill": "topic_classifier", "contains": ["Topic"]},
            {"skill": "text_rewriter", "contains": ["Rewritten"]},
        ],
        {"contains": ["Rewritten"]},
    ),
]


def main() -> None:
    seed_tasks = json.loads(MINI_PATH.read_text(encoding="utf-8"))
    all_tasks = seed_tasks + NEW_DEV_TASKS
    task_ids = [task["task_id"] for task in all_tasks]
    duplicates = [task_id for task_id, count in Counter(task_ids).items() if count > 1]
    if duplicates:
        raise SystemExit(f"Duplicate task_id values: {duplicates}")

    DEV_PATH.write_text(
        json.dumps(all_tasks, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    counts = Counter(task["task_type"] for task in all_tasks)
    print(f"Wrote {len(all_tasks)} tasks to {DEV_PATH}")
    print(f"Counts: {dict(counts)}")
    print(f"Added dev tasks: {NEW_DEV_TASKS[0]['task_id']} - {NEW_DEV_TASKS[-1]['task_id']}")


if __name__ == "__main__":
    main()
